### ISSUE TITLE
"Outer Before Inner Walls" missing

### ISSUE THREAD

**Issue by Triangulix** [5axes/ProfilAnalyser#3]
Hi

I just noticed that the setting "Outer Before Inner Walls" is not included in the exported tables. Maybe there are other settings missing, too.

Best Regards

**Comment by 5axes** [comment]
Works for me , 
![image](https://user-images.githubusercontent.com/11015345/132173461-854b51d8-b59c-489a-a55d-5177ff382c8e.png)
As well in the profile comparison
![image](https://user-images.githubusercontent.com/11015345/132173614-87bded18-6997-4e68-bb86-4e4c71873c35.png)

**Comment by Triangulix** [comment]
Unfortunately it doesn't work for me.
![Unbenannt](https://user-images.githubusercontent.com/43012099/132421998-52227d88-458e-4267-9252-19a5ab0e0a1c.PNG)

**Comment by Triangulix** [comment]
Is it possible that I'm using an incompatible version combination?
Cura 4.8.0 and plugin 1.1.2.

**Comment by 5axes** [comment]
No it's not possible. But as you are on the comparison profiles function. It's normal if you have never modified this parameter. If it's just the normal setting, then this parameter is not save on the profiles, si you cannot see it.

**Comment by Triangulix** [comment]
I just tested this and it seems to be the solution. Weird. I'm pretty sure there are lots of fields in the export which I have never changed in a profile.

**Comment by 5axes** [comment]
That's the problem with the profile management with Cura. Just the modified parameters regarding the base profile are exported, so if the base profile change (ie modification between two release) you are not sure to get the same result. But concerning the function of this plugin used to compare different profiles if a parameter is not present it's not an issue, that's just because they are not different and they are using the base value. If you want to check or analyze a profile you need to use the second function : Analyse current profile
